### ISSUE TITLE
.css depreciation warnings with sass-rails 5.0.4 gem

### ISSUE THREAD

**Issue by jonmarinello** [activeadmin-plugins/active_admin_theme#19]
`DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename /Users/jonmarinello/.rvm/gems/ruby-2.2.3/gems/active_admin_theme-1.0.2/app/assets/stylesheets/wigu/active_admin_theme.css.scss to /Users/jonmarinello/.rvm/gems/ruby-2.2.3/gems/active_admin_theme-1.0.2/app/assets/stylesheets/wigu/active_admin_theme.scss. (called from realtime at /Users/jonmarinello/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303)`

Not sure when the `.css` extension was retired but this started happening to me in 5.0.4 of the sass-rails gem.

**Comment by jonmarinello** [comment]
Looking at the code I see this was already addressed a couple of months ago. Can you publish a new gem version (1.0.3) with this fix?

**Comment by Fivell** [comment]
@jonmarinello , https://rubygems.org/gems/active_admin_theme/versions/1.0.3

**Comment by jonmarinello** [comment]
@Fivell :+1:
