### ISSUE TITLE
sidebar widget?

### ISSUE THREAD

**Issue by niksfirefly** [activeadmin-plugins/active_admin_theme#20]
I see in INFO sidebar tabs widget
Is it arbre widget?

**Comment by Fivell** [comment]
@niksfirefly, take a look
https://github.com/activeadmin/activeadmin/blob/b44b4f4896ef78b50c35c82a343356d68b937cde/docs/6-show-pages.md#tabs and https://github.com/activeadmin/activeadmin/pull/3771

**Comment by niksfirefly** [comment]
Ok so basically it is arbre's tabs but with custom css style right?
Thank you - I try your theme to see it in action
