### ISSUE TITLE
Wrong H3 titles margin

### ISSUE THREAD

**Issue by af23me** [activeadmin-plugins/active_admin_theme#26]
Active Admin version: 1.3.1

![2018-10-05 11 37 07](https://user-images.githubusercontent.com/12969204/46525156-8ad89e80-c893-11e8-98db-2db1370fa0f3.png)
![2018-10-05 11 37 38](https://user-images.githubusercontent.com/12969204/46525169-93c97000-c893-11e8-8559-3ce87fe6c492.png)

**Comment by mrhillman** [comment]
Will there be a new release with this included?
